export const questions = [
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: En la mesa ______ muchos libros y carpetas.", correctAnswer: "Hay", explanation: "Se usa 'Hay' (del verbo haber) para indicar la existencia de algo." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¡______! Me he hecho daño en la pierna.", correctAnswer: "Ay", explanation: "Se usa '¡Ay!' como una interjección para expresar dolor o sorpresa." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: Coloca las llaves y el abrigo ______.", correctAnswer: "ahí", explanation: "Se usa 'ahí' como un adverbio de lugar para indicar una ubicación." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: No ______ pan ni leche en casa.", correctAnswer: "hay", explanation: "Se usa 'hay' para indicar la existencia (o en este caso, la no existencia) de algo." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¡______! Qué día tan largo llevo.", correctAnswer: "Ay", explanation: "Se usa '¡Ay!' como una interjección para expresar un sentimiento, como el cansancio o la queja." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: Deja el móvil encima del sofá, ______.", correctAnswer: "ahí", explanation: "Se usa 'ahí' para indicar el lugar donde se debe dejar el móvil." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¿Cuántos estudiantes ______ hoy en clase?", correctAnswer: "hay", explanation: "Se usa 'hay' para preguntar por la existencia o cantidad de algo." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ______ una tienda nueva en la esquina.", correctAnswer: "Hay", explanation: "Se usa 'Hay' para indicar la existencia de la tienda." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¡______! ¡Se me ha roto el vaso!", correctAnswer: "Ay", explanation: "Se usa '¡Ay!' como una interjección para expresar sorpresa o disgusto." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: Pon los platos y los vasos ______.", correctAnswer: "ahí", explanation: "Se usa 'ahí' para indicar el lugar donde se deben poner los platos y vasos." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: No ______ tiempo para terminar el trabajo.", correctAnswer: "hay", explanation: "Se usa 'hay' para indicar la no existencia de tiempo." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¡______! ¡Me he quemado con el café!", correctAnswer: "Ay", explanation: "Se usa '¡Ay!' como una interjección para expresar dolor." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ______ un concierto este fin de semana.", correctAnswer: "Hay", explanation: "Se usa 'Hay' para indicar la existencia de un evento." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: El cargador está ______, al lado de la cama.", correctAnswer: "ahí", explanation: "Se usa 'ahí' para indicar la ubicación del cargador." },
    { type: 'fill-in-the-blank', questionText: "Completa las siguientes frases utilizando Hay, ahí y ay: ¡______, qué dolor de cabeza!", correctAnswer: "Ay", explanation: "Se usa '¡Ay!' como una interjección para expresar dolor." }
];