
export const questions = [
    { id: 't4-1', type: 'multiple-choice', questionText: "1. ¿Quién puede conducir carretillas automotoras?", options: ["Cualquier trabajador", "Solo los autorizados por el jefe", "Solo los que hayan recibido FORMACIÓN ESPECÍFICA"], correctAnswerIndex: 2 },
    { id: 't4-2', type: 'multiple-choice', questionText: "2. Según las NTP, ¿qué edad mínima debe tener un operador?", options: ["Mayor de 18 años", "16 años", "21 años"], correctAnswerIndex: 0 },
    { id: 't4-3', type: 'multiple-choice', questionText: "3. ¿Qué requisito psicofísico debe cumplir el operador?", options: ["Saber nadar", "Aptitudes psicofísicas y sensoriales adecuadas", "Tener buena visión nocturna"], correctAnswerIndex: 1 },
    { id: 't4-4', type: 'multiple-choice', questionText: "4. ¿Quién debe autorizar especialmente al operador?", options: ["El compañero", "El técnico de prevención", "El empresario"], correctAnswerIndex: 2 },
    { id: 't4-5', type: 'multiple-choice', questionText: "5. Para circular en vía pública, ¿qué documento es obligatorio?", options: ["Carné", "Certificado de estudios", "Permiso de armas"], correctAnswerIndex: 0 },
    { id: 't4-6', type: 'multiple-choice', questionText: "6. ¿Qué tipo de carretilla usa motor de combustión?", options: ["Eléctrica", "Térmica", "Híbrida"], correctAnswerIndex: 1 },
    { id: 't4-7', type: 'multiple-choice', questionText: "7. ¿Qué combustible NO pertenece a motor de explosión?", options: ["Gasoil", "GLP", "Gasolina"], correctAnswerIndex: 0 },
    { id: 't4-8', type: 'multiple-choice', questionText: "8. ¿Qué tipo de batería se carga como un móvil?", options: ["Ácido-plomo", "Níquel-cadmio", "Litio"], correctAnswerIndex: 2 },
    { id: 't4-9', type: 'multiple-choice', questionText: "9. ¿Cuándo se deben cargar las baterías de ácido-plomo?", options: ["Al 50%", "Cuando bajan al 20%", "Solo al final del turno"], correctAnswerIndex: 1 },
    { id: 't4-10', type: 'multiple-choice', questionText: "10. Durante la carga de batería ácido-plomo, ¿qué está prohibido?", options: ["Acercar llamas", "Usar guantes", "Ventilar el lugar"], correctAnswerIndex: 0 },
    { id: 't4-11', type: 'multiple-choice', questionText: "11. ¿Qué ventaja tiene la batería de litio?", options: ["Es más barata", "Dura menos", "Mayor densidad energética en menos espacio"], correctAnswerIndex: 2 },
    { id: 't4-12', type: 'multiple-choice', questionText: "12. ¿Cuándo se rellena de agua destilada la batería?", options: ["Antes de cargar", "Después de una carga completa", "Durante el uso"], correctAnswerIndex: 1 },
    { id: 't4-13', type: 'multiple-choice', questionText: "13. ¿Hasta dónde se llena de agua la batería?", options: ["Cubriendo las placas de plomo", "Hasta el borde", "Hasta la mitad"], correctAnswerIndex: 0 },
    { id: 't4-14', type: 'multiple-choice', questionText: "14. Si falta agua en la batería, ¿qué ocurre?", options: ["Se calienta menos", "No funciona", "Se carga más rápido"], correctAnswerIndex: 1 },
    { id: 't4-15', type: 'multiple-choice', questionText: "15. ¿Qué se debe evitar en las conexiones de batería?", options: ["Limpiarlas", "El sulfatado", "Apretarlas"], correctAnswerIndex: 1 },
    { id: 't4-16', type: 'multiple-choice', questionText: "16. En baterías antiguas, ¿qué hacer con los tapones?", options: ["Quitarlos permanentemente", "Cerrarlos siempre", "Abrirlos para respiración (si la máquina lo requiere)"], correctAnswerIndex: 2 },
    { id: 't4-17', type: 'multiple-choice', questionText: "17. Al repostar carretilla térmica, ¿qué está prohibido?", options: ["Parar el motor", "Acercar llamas", "Usar EPIs"], correctAnswerIndex: 1 },
    { id: 't4-18', type: 'multiple-choice', questionText: "18. ¿Para qué sirve el espejo retrovisor?", options: ["Para ver la carga", "Es de ayuda, no se conduce con él", "Para conducir"], correctAnswerIndex: 1 },
    { id: 't4-19', type: 'multiple-choice', questionText: "19. ¿Qué protege el pórtico de seguridad?", options: ["Las ruedas", "Al conductor ante caída de objetos y vuelco", "El motor"], correctAnswerIndex: 1 },
    { id: 't4-20', type: 'multiple-choice', questionText: "20. ¿Cuándo es obligatorio el girofaro?", options: ["Solo de noche", "Solo en almacén", "En vía pública"], correctAnswerIndex: 2 },
    { id: 't4-21', type: 'multiple-choice', questionText: "21. ¿Qué indica el pitido de marcha atrás?", options: ["Batería baja", "La carretilla va marcha atrás", "Freno puesto"], correctAnswerIndex: 1 },
    { id: 't4-22', type: 'multiple-choice', questionText: "22. ¿Qué función tiene la luz BlueSpot?", options: ["Sirve de freno", "Indica que la máquina está en movimiento", "Ilumina la carga"], correctAnswerIndex: 1 },
    { id: 't4-23', type: 'multiple-choice', questionText: "23. ¿Qué ventaja tiene el volante con servodirección?", options: ["Gira solo", "Menos esfuerzo en espacios pequeños", "Es más rápido"], correctAnswerIndex: 1 },
    { id: 't4-24', type: 'multiple-choice', questionText: "24. ¿Qué mano va en el pomo al conducir?", options: ["Ambas", "Derecha", "Izquierda"], correctAnswerIndex: 2 },
    { id: 't4-25', type: 'multiple-choice', questionText: "25. ¿De cuántos trozos puede estar compuesto el mástil?", options: ["1", "Hasta 3", "2"], correctAnswerIndex: 1 },
    { id: 't4-26', type: 'multiple-choice', questionText: "26. ¿Qué evita el respaldo de carga?", options: ["Que se mueva lateralmente", "Que caiga hacia atrás", "Que la carga se deslice adelante"], correctAnswerIndex: 1 },
    { id: 't4-27', type: 'multiple-choice', questionText: "27. Los brazos de la horquilla deben estar:", options: ["Curvados", "Rectos y paralelos al suelo", "Inclinados"], correctAnswerIndex: 1 },
    { id: 't4-28', type: 'multiple-choice', questionText: "28. ¿Cuándo se permite cargar sacos reduciendo visibilidad?", options: ["Solo de noche", "Nunca", "Cuando son sacos o carga muy pesada"], correctAnswerIndex: 2 },
    { id: 't4-29', type: 'multiple-choice', questionText: "29. ¿Dónde está normalmente el eje motriz?", options: ["Lateral", "Delantero", "Trasero"], correctAnswerIndex: 1 },
    { id: 't4-30', type: 'multiple-choice', questionText: "30. ¿Qué son las ruedas directrices?", options: ["Las de carga", "Las que giran al mover el volante", "Las que empujan"], correctAnswerIndex: 1 },
    { id: 't4-31', type: 'multiple-choice', questionText: "31. ¿Qué es el estribo?", options: ["El volante", "Donde pisamos para subir (NO SALTAR AL BAJAR)", "El asiento"], correctAnswerIndex: 1 },
    { id: 't4-32', type: 'multiple-choice', questionText: "32. ¿Para qué sirve el asa de acceso?", options: ["Para cargar", "Punto de apoyo para subir", "Para frenar"], correctAnswerIndex: 1 },
    { id: 't4-33', type: 'multiple-choice', questionText: "33. Si la carretilla tiene cinturón, ¿qué hacer?", options: ["Quitarlo", "Ponérselo", "No usarlo"], correctAnswerIndex: 1 },
    { id: 't4-34', type: 'multiple-choice', questionText: "34. ¿Por qué el asiento tiene suspensión?", options: ["Porque la carretilla no tiene amortiguación", "Para ir más rápido", "Para evitar daños en la espalda"], correctAnswerIndex: 2 },
    { id: 't4-35', type: 'multiple-choice', questionText: "35. ¿Por dónde salen los humos del motor?", options: ["Por las ruedas", "Por el mástil", "Por el tubo de escape"], correctAnswerIndex: 2 },
    { id: 't4-36', type: 'multiple-choice', questionText: "36. ¿Qué tipo de rueda tiene mejor amortiguación?", options: ["Superelástica", "Maciza", "Neumática"], correctAnswerIndex: 2 },
    { id: 't4-37', type: 'multiple-choice', questionText: "37. ¿Qué rueda tiene mayor capacidad de carga?", options: ["Maciza", "Neumática", "Superelástica"], correctAnswerIndex: 0 },
    { id: 't4-38', type: 'multiple-choice', questionText: "38. ¿Cuántas capas tiene la rueda superelástica?", options: ["2", "1", "3"], correctAnswerIndex: 2 },
    { id: 't4-39', type: 'multiple-choice', questionText: "39. ¿Qué ruedas marcan menos el suelo?", options: ["Ambas igual", "Blancas (antihuellas)", "Negras"], correctAnswerIndex: 1 },
    { id: 't4-40', type: 'multiple-choice', questionText: "40. ¿Cuántos puntos de apoyo mínimos son seguros?", options: ["5", "2", "3 o 4"], correctAnswerIndex: 2 },
    { id: 't4-41', type: 'multiple-choice', questionText: "41. ¿Qué carretilla puede girar a 90°?", options: ["Ambas", "3 ruedas", "4 ruedas"], correctAnswerIndex: 1 },
    { id: 't4-42', type: 'multiple-choice', questionText: "42. Color de seguridad para advertencia:", options: ["Verde", "Amarillo o naranja", "Azul"], correctAnswerIndex: 1 },
    { id: 't4-43', type: 'multiple-choice', questionText: "43. Color para obligatoriedad:", options: ["Amarillo", "Rojo", "Azul"], correctAnswerIndex: 2 },
    { id: 't4-44', type: 'multiple-choice', questionText: "44. Color para salvamento o socorro:", options: ["Verde", "Azul", "Rojo"], correctAnswerIndex: 0 },
    { id: 't4-45', type: 'multiple-choice', questionText: "45. Color para lucha contra el fuego:", options: ["Blanco", "Rojo", "Verde"], correctAnswerIndex: 1 },
    { id: 't4-46', type: 'multiple-choice', questionText: "46. ¿Qué EPI es obligatorio para el carretillero?", options: ["Gafas de sol", "Casco", "Botas y guantes"], correctAnswerIndex: 2 },
    { id: 't4-47', type: 'multiple-choice', questionText: "47. Riesgo en estanterías:", options: ["Carga baja", "Mal estado del suelo", "Suelo en buen estado"], correctAnswerIndex: 1 },
    { id: 't4-48', type: 'multiple-choice', questionText: "48. Al comenzar actividad, ¿qué se revisa primero?", options: ["El café", "Control fuera de la carretilla", "El móvil"], correctAnswerIndex: 1 },
    { id: 't4-49', type: 'multiple-choice', questionText: "49. Al subir a la carretilla, ¿qué se hace en último lugar?", options: ["Bajar las uñas", "Arrancar", "Abrochar cinturón (si lo tiene)"], correctAnswerIndex: 2 },
    { id: 't4-50', type: 'multiple-choice', questionText: "50. Al estacionar, ¿dónde deben estar las uñas?", options: ["Retraídas", "Basculadas adelante, punta en el suelo", "Elevadas"], correctAnswerIndex: 1 },
    { id: 't4-51', type: 'multiple-choice', questionText: "51. ¿Qué es el centro de gravedad combinado?", options: ["Solo de la carga", "Carga + carretilla", "Solo de la carretilla"], correctAnswerIndex: 1 },
    { id: 't4-52', type: 'multiple-choice', questionText: "52. ¿Cómo calcular la capacidad de carga?", options: ["Sumar los dígitos", "2 últimos dígitos del modelo × 100", "Mirar el color"], correctAnswerIndex: 1 },
    { id: 't4-53', type: 'multiple-choice', questionText: "53. La inercia de la carga:", options: ["Desaparece al parar", "Se controla con freno", "No se puede controlar"], correctAnswerIndex: 2 },
    { id: 't4-54', type: 'multiple-choice', questionText: "54. La fuerza centrífuga te lleva:", options: ["Hacia arriba", "Al exterior", "Hacia dentro"], correctAnswerIndex: 1 },
    { id: 't4-55', type: 'multiple-choice', questionText: "55. Con carga, ¿a qué altura debe ir?", options: ["1 metro", "50 cm", "15 cm del suelo"], correctAnswerIndex: 2 },
    { id: 't4-56', type: 'multiple-choice', questionText: "56. Movimiento básico de carretilla frontal:", options: ["Solo elevación", "Traslación, elevación, basculante, desplazador", "Rotación 360°"], correctAnswerIndex: 1 },
    { id: 't4-57', type: 'multiple-choice', questionText: "57. Característica de carretilla retráctil:", options: ["Lleva cinturón", "Para pasillos anchos", "Para pasillos estrechos, gira sobre sí misma"], correctAnswerIndex: 2 },
    { id: 't4-58', type: 'multiple-choice', questionText: "58. ¿Cuándo se permite elevar personas?", options: ["Nunca", "Todos los días", "Solo carácter excepcional y puntual"], correctAnswerIndex: 2 },
    { id: 't4-59', type: 'multiple-choice', questionText: "59. Para elevar personas, ¿cuántas personas mínimo?", options: ["3", "2", "1"], correctAnswerIndex: 0 },
    { id: 't4-60', type: 'multiple-choice', questionText: "60. ¿Quién debe estar presente al elevar personas?", options: ["Solo el jefe", "Técnico de prevención, operario y tercera persona", "Solo el operario"], correctAnswerIndex: 1 },
    { id: 't4-61', type: 'multiple-choice', questionText: "61. ¿Qué equipo de protección individual es obligatorio para el carretillero?", options: ["Casco", "Ropa de trabajo", "Botas y guantes"], correctAnswerIndex: 2 },
    { id: 't4-62', type: 'multiple-choice', questionText: "62. ¿Qué situación puede provocar un accidente en el entorno de las carretillas?", options: ["Mal estado del suelo, transportar carga en altura, malas reacciones del carretillero", "Realizar varios movimientos a la vez", "No existe control del entorno"], correctAnswerIndex: 0 },
    { id: 't4-63', type: 'multiple-choice', questionText: "63. ¿Qué es importante considerar para la estabilidad de la carretilla?", options: ["Capacidad de carga", "Centro de gravedad de la carga", "Centro de gravedad de la carga, centro de gravedad de la carretilla, capacidad de carga"], correctAnswerIndex: 2 },
    { id: 't4-64', type: 'multiple-choice', questionText: "64. ¿Qué es la fuerza de inercia en una carretilla?", options: ["La que controla la aceleración y el frenado (carretilla), mientras la carga tiene su propia inercia", "La que mantiene la carretilla en movimiento", "La que inclina la carretilla"], correctAnswerIndex: 0 },
    { id: 't4-65', type: 'multiple-choice', questionText: "65. ¿Qué se debe hacer al conducir una carretilla en zonas con poca visibilidad?", options: ["No utilizar avisadores acústicos", "Reducir la velocidad", "Aumentar la velocidad"], correctAnswerIndex: 1 }
];
