
export const questions = [
    // Parte 1: Ordene las palabras...
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Qué", "tiene", "Julián", "en la mano?"], correctAnswer: "¿Qué tiene Julián en la mano?", explanation: "კითხვითი ნაწილაკი Qué (რა) ყოველთვის იწყებს წინადადებას.", level: 'A1' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Con quién", "está bailando", "Eloísa?"], correctAnswer: "¿Con quién está bailando Eloísa?", explanation: "Con (ვისთან) წინდებული უნდა დაურთოთ კითხვით ნაწილაკს quién (ვინ), რათა ჩამოყალიბდეს Con quién (ვისთან).", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Para quién", "es", "ese anillo?"], correctAnswer: "¿Para quién es ese anillo?", explanation: "Para (ვისთვის) წინდებული უნდა დაურთოთ კითხვით ნაწილაკს quién (ვინ), რათა ჩამოყალიბდეს Para quién (ვისთვის).", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Qué", "pasó", "anoche?"], correctAnswer: "¿Qué pasó anoche?", explanation: "კითხვითი ნაწილაკი Qué (რა) იწყებს წინადადებას, რასაც მოჰყვება ზმნა და შემდეგ დრის განმსაზღვრელი.", level: 'A1' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿De quién", "es", "esa bolsa?"], correctAnswer: "¿De quién es esa bolsa?", explanation: "De (ვისი) წინდებული უნდა დაურთოთ კითხვით ნაწილაკს quién (ვინ), რათა ჩამოყალიბდეს De quién (ვისი).", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Qué", "te", "han regalado", "tus padres?"], correctAnswer: "¿Qué te han regalado tus padres?", explanation: "კითხვითი ნაწილაკი Qué (რა) იწყებს წინადადებას და ამ შემთხვევაში არის ზმნის han regalado პირდაპირი დამატება.", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Con qué", "has abierto", "la puerta?"], correctAnswer: "¿Con qué has abierto la puerta?", explanation: "Con (რათი/რით) წინდებული უნდა დაურთოთ კითხვით ნაწილაკს qué (რა), რათა ჩამოყალიბდეს Con qué (რათი).", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Quién", "está escribiendo", "una novela?"], correctAnswer: "¿Quién está escribiendo una novela?", explanation: "კითხვითი ნაწილაკი Quién (ვინ) იწყებს წინადადებას და არის მოქმედების შემსრულებელი (სუბიექტი).", level: 'A1' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Qué", "quiere", "María?"], correctAnswer: "¿Qué quiere María?", explanation: "კითხვითი ნაწილაკი Qué (რა) იწყებს წინადადებას და არის ზმნის quiere პირდაპირი დამატება.", level: 'A1' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿Quién", "quiere", "a María?"], correctAnswer: "¿Quién quiere a María?", explanation: "კითხვითი ნაწილაკი Quién (ვინ) იწყებს წინადადებას და არის მოქმედების შემსრულებელი (სუბიექტი). A María არის პირდაპირი დამატება.", level: 'A2' },
    { type: 'order-words', questionText: "Ordena las palabras para formar la pregunta:", words: ["¿De qué", "es", "la sopa?"], correctAnswer: "¿De qué es la sopa?", explanation: "De (რისგან) წინდებული უნდა დაურთოთ კითხვით ნაწილაკს qué (რა), რათა ჩამოყალიბდეს De qué (რისგან).", level: 'A2' },

    // Parte 2: Complete las preguntas...
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ te ha regalado ese collar?", correctAnswer: ["Quién", "Quien"], explanation: "კითხვა ეძებს პიროვნებას (მოქმედების შემსრულებელს), ამიტომ ვიყენებთ Quién.", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿De ______ es esta pluma?", correctAnswer: "quién", explanation: "კითხვა ეძებს პიროვნებას, რომელსაც ეკუთვნის კალამი. De წინდებულთან ერთად ვიყენებთ quién (ვისი).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ miel tomas normalmente?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს რაღაცას/ნივთს (თაფლის ტიპს ან ბრენდს), ამიტომ ვიყენებთ Qué.", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿Con ______ fuiste a Bolivia?", correctAnswer: "quién", explanation: "კითხვა ეძებს პიროვნებას (Con წინდებულთან ერთად - ვისთან).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ estás haciendo?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს მოქმედებას ან საქმიანობას (რას აკეთებ), ამიტომ ვიყენებთ Qué.", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ van a jugar en el equipo esta semana?", correctAnswer: ["Quiénes", "Quienes"], explanation: "კითხვა ეძებს პიროვნებთა ჯგუფს (მოქმედების შემსრულებლებს), ამიტომ ვიყენებთ Quiénes (ვინ - მრავლობითი).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ libros le gustan a Teresa?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს რაღაცას/ნივთს (წიგნების ტიპს ან ჟანრს), ამიტომ ვიყენებთ Qué.", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿Con ______ has abierto el paquete?", correctAnswer: "qué", explanation: "კითხვა ეძებს ინსტრუმენტს ან საშუალებას (Con წინდებულთან ერთად - რათი), ამიტომ ვიყენებთ qué.", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿A ______ viste anoche en la fiesta?", correctAnswer: "quién", explanation: "კითხვა ეძებს პიროვნებას (A წინდებულთან ერთად - ვინ), ამიტომ ვიყენებთ quién.", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ viste anoche en la tele?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს რაღაცას/ნივთს (ფილმს, პროგრამას და ა.შ.), ამიტომ ვიყენებთ Qué.", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Completa la pregunta con 'qué' o 'quién/quiénes': ¿______ quería Julián?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს რაღაცას/ნივთს (ობიექტს), ამიტომ ვიყენებთ Qué.", level: 'A1' },

    // Parte 3: Formule preguntas...
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Ayer estuve con Águeda.<br>-¿______ estuviste ayer?", correctAnswer: ["Con quién", "con quien"], explanation: "კითხვა ეძებს პიროვნებას (con Águeda), ამიტომ ვიყენებთ Con quién.", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Esa silla está hecha de cuerda.<br>-¿______ está hecha esa silla?", correctAnswer: ["De qué", "de que"], explanation: "კითხვა ეძებს მასალას (de cuerda), ამიტომ ვიყენებთ De qué (რისგან).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Normalmente comemos con pan de molde.<br>-¿______ pan coméis?", correctAnswer: ["Con qué", "con que"], explanation: "კითხვა ეძებს რაღაცას, რასაც მიირთმევენ/იყენებენ (con pan), ამიტომ ვიყენებთ Con qué (რას/რათი).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Alfonso quiere comprarse un CD.<br>-¿______ quiere comprarse Alfonso?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს ობიექტს (un CD), ამიტომ ვიყენებთ Qué (რა).", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Estas gafas son de Pablo.<br>-¿______ son esas gafas?", correctAnswer: ["De quién", "de quien"], explanation: "კითხვა ეძებს პიროვნებას (de Pablo), ამიტომ ვიყენებთ De quién (ვისი).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Georgina está trabajando con su madre.<br>-¿______ está trabajando Georgina?", correctAnswer: ["Con quién", "con quien"], explanation: "კითხვა ეძებს პიროვნებას (con su madre), ამიტომ ვიყენებთ Con quién (ვისთან).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Han ganado Eduardo y Marisa.<br>-¿______ han ganado?", correctAnswer: ["Quiénes", "Quienes"], explanation: "კითხვა ეძებს პიროვნებთა ჯგუფს (Eduardo y Marisa), ამიტომ ვიყენებთ Quiénes (ვინ - მრავლობითი).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Mira. Esos chicos están bailando.<br>-¿______ están haciendo esos chicos?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს მოქმედებას/საქმიანობას (bailando), ამიტომ ვიყენებთ Qué (რას).", level: 'A1' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Belinda no quiere a Ariel.<br>-¿______ no quiere Belinda?", correctAnswer: ["A quién", "a quien"], explanation: "კითხვა ეძებს პიროვნებას (a Ariel), ამიტომ ვიყენებთ A quién (ვინ).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Estas flores son para mi abuela.<br>-¿______ son esas flores?", correctAnswer: ["Para quién", "para quien"], explanation: "კითხვა ეძებს პიროვნებას (para mi abuela), ამიტომ ვიყენებთ Para quién (ვისთვის).", level: 'A2' },
    { type: 'fill-in-the-blank', questionText: "Formula la pregunta para la respuesta dada: -Me han regalado unos bombones.<br>-¿______ te han regalado?", correctAnswer: ["Qué", "Que"], explanation: "კითხვა ეძებს ობიექტს (unos bombones), ამიტომ ვიყენებთ Qué (რა).", level: 'A1' },
];
