
export const questions = [
    // Page 1
    { questionText: "1. ¿Cuál es el objetivo principal en la cima de la pirámide logística?", options: ["Reducir costes al mínimo", "Dar al cliente lo que quiere", "Optimizar el tiempo de entrega", "Asegurar la calidad de los recursos"], correctAnswerIndex: 1 },
    { questionText: "2. En la pirámide logística, ¿qué elemento sostiene la base del proceso?", options: ["La calidad del producto", "Recursos/costes y tiempo", "La trazabilidad de la mercancía", "La comunicación entre equipos"], correctAnswerIndex: 1 },
    { questionText: "3. El nivel medio de la pirámide logística indica que la calidad es fundamental para alcanzar el objetivo principal.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "4. ¿Quién es el cliente externo?", options: ["El trabajador del proceso posterior", "El que nos vende bienes y servicios", "El que paga por nuestros bienes o servicios", "El compañero que realiza la tarea anterior"], correctAnswerIndex: 2 },
    { questionText: "5. ¿Qué define al proveedor interno?", options: ["El que recibe el trabajo en el proceso posterior", "El que nos vende bienes externos", "El trabajador respecto del proceso anterior", "El consumidor final de la cadena"], correctAnswerIndex: 2 },
    // Page 2
    { questionText: "6. El cliente interno es el transportista que entrega la mercancía al almacén.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "7. ¿Qué significa eficacia en logística?", options: ["Conseguir los objetivos con el menor número de recursos", "Reducir el tiempo de almacenamiento", "Alcanzar los objetivos", "Minimizar los errores de facturación"], correctAnswerIndex: 2 },
    { questionText: "8. La eficiencia se centra en lograr un producto con un coste logístico aceptable.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "9. ¿Cuál es la primera actividad en la secuencia de un almacén?", options: ["Área de picking", "Muelle / Área de descarga", "Área de expedición", "Playa de envíos"], correctAnswerIndex: 1 },
    { questionText: "10. El flujo del almacén sigue: proveedores → almacén → producción → almacén (producto final) → cliente externo.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 3
    { questionText: "11. ¿Qué incluye el área de almacenaje?", options: ["Solo la zona de picking", "Silos o zonas buffer/pulmón de ubicación", "Playa de expediciones", "Área de envíos"], correctAnswerIndex: 1 },
    { questionText: "12. Los espacios de reciclaje forman parte de los espacios auxiliares de un almacén.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "13. ¿Cuál es una característica de la descarga en muelle (trasera)?", options: ["Requiere mucho espacio exterior para maniobras", "Se aplica el principio LIFO (Last In, First Out)", "Solo se usa para vehículos abiertos", "Implica mayor riesgo de caída de mercancía"], correctAnswerIndex: 1 },
    { questionText: "14. En la descarga en plano se necesita carretilla elevadora o apilador eléctrico.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "15. ¿Qué documento acredita la entrega cuando el cliente lo firma?", options: ["Carta de porte", "Factura comercial", "Albarán", "Pedido de compra"], correctAnswerIndex: 2 },
    // Page 4
    { questionText: "16. El proceso de recepción comienza con la verificación del precinto del vehículo.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "17. ¿Qué se comprueba en la descarga durante la recepción?", options: ["Solo la cantidad", "Cantidad, desperfectos y manipulaciones", "Coste logístico total", "Motivación del transportista"], correctAnswerIndex: 1 },
    { questionText: "18. La verificación en recepción puede realizarse con PDA para mayor precisión.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "19. ¿Para qué sirve el área de cuarentena o devolución?", options: ["Almacenar productos finales listos", "Guardar mercancía en espera de devolución o revisión", "Preparar pedidos de picking", "Reciclar embalajes vacíos"], correctAnswerIndex: 1 },
    { questionText: "20. El área de cuarentena debe estar cerrada con llave para evitar robos.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "21. ¿Qué provoca un cuello de botella en el flujo del almacén?", options: ["Aumento de rotación de stock", "El flujo se detiene por falta de ritmo", "Mayor eficiencia en expedición", "Reducción de costes en personal"], correctAnswerIndex: 1 },
    // Page 5
    { questionText: "22. Una consecuencia de un cuello de botella para el cliente externo es la pérdida de imagen.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "23. ¿Cuál es una causa común de cuello de botella?", options: ["Exceso de inversión en maquinaria", "Maquinaria defectuosa o obsoleta", "Formación excesiva del personal", "Organización perfecta de tiempos"], correctAnswerIndex: 1 },
    { questionText: "24. Para el cliente interno, un cuello de botella implica personal parado y aumento de costes.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "25. ¿Qué tipo de almacén contiene materia prima y productos semielaborados?", options: ["Comercial", "Industrial", "De tránsito", "Para mercancías peligrosas"], correctAnswerIndex: 1 },
    { questionText: "26. Los almacenes comerciales son el punto final de la cadena y contienen mercancía para el cliente final.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 6
    { questionText: "27. ¿Qué diferencia a un almacén cubierto de uno descubierto?", options: ["Ofrece menos seguridad pero es más barato", "Protege del clima y ofrece más seguridad, pero es más caro", "Se usa solo para picking", "No requiere espacios auxiliares"], correctAnswerIndex: 1 },
    { questionText: "28. Los almacenes para mercancías peligrosas no siguen una normativa específica.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "29. ¿Qué define a un grupo?", options: ["Conjunto de personas con objetivos comunes y sinergia", "Conjunto de personas que trabajan juntas sin compartir metas", "Equipo con habilidades complementarias", "Personal motivado con líder fijo"], correctAnswerIndex: 0 },
    { questionText: "30. Un equipo eficaz requiere sinergia, donde el resultado es superior a la suma de las partes individuales.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "31. ¿Cuáles son las tres grandes áreas de gestión del almacén?", options: ["Recepción, picking y salida", "Operativo, documental (administrativo) y comercial", "Industrial, comercial y de tránsito"], correctAnswerIndex: 1 },
    // Page 7
    { questionText: "32. El espíritu de equipo implica trabajar de forma coordinada con un líder y compromiso.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "33. ¿Qué es la comunicación?", options: ["Solo el intercambio verbal entre emisor y receptor", "Capacidad de relacionarse con el entorno (emisor → mensaje → receptor)", "Herramienta solo para resolver conflictos", "Proceso que ignora la asertividad"], correctAnswerIndex: 1 },
    { questionText: "34. La comunicación en el almacén puede ser verbal o no verbal.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "35. ¿Qué caracteriza la asertividad en la comunicación?", options: ["Imponer decisiones sin reconocer errores", "Resolver conflictos buscando soluciones y reconociendo errores", "Evitar toda relación con el entorno", "Cambiar a los demás sin auto-reflexión"], correctAnswerIndex: 1 },
    { questionText: "36. Para evaluar la calidad del trabajo, una pregunta clave es: \"¿Se cumplen los objetivos?\".", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 8
    { questionText: "37. ¿Cuál es un indicador de calidad en el almacén?", options: ["Aumento intencional de tiempo perdido en expedición", "Tasa de rotura de stock", "Ignorar el servicio postventa", "Errores voluntarios en facturación"], correctAnswerIndex: 1 },
    { questionText: "38. El índice de satisfacción del cliente no es un indicador de calidad.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "39. ¿Qué es el estándar GS1-128?", options: ["Un sistema para control de stock mínimo", "Sistema de códigos de barras para identificación de productos", "Método de pago internacional", "Herramienta para gestión de personal"], correctAnswerIndex: 1 },
    { questionText: "40. Los productos se clasifican jerárquicamente: Familia → Subfamilia → Grupo → Subgrupo.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "41. ¿Qué permite la trazabilidad en la cadena de suministro?", options: ["Solo reducir costes de transporte", "Seguimiento (tracking y tracing) del lote, fecha y hora del producto", "Aumentar el tiempo de picking", "Eliminar la necesidad de PDA"], correctAnswerIndex: 1 },
    // Page 9
    { questionText: "42. El EDI (Intercambio Electrónico de Datos) no se usa para intercambiar documentos digitales.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "43. ¿Qué ventaja ofrece una PDA en el movimiento de mercancía?", options: ["Aumenta los errores y el tiempo", "Facilita codificación, identificación y trazabilidad, reduciendo costes", "Solo se usa para comunicación verbal", "Elimina la necesidad de espacios auxiliares"], correctAnswerIndex: 1 },
    { questionText: "44. Una PDA reduce el tiempo de trabajo y aumenta la seguridad en el almacén.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "45. ¿Qué incluye el espacio dedicado a la logística inversa en un almacén?", options: ["Solo oficinas y vestuarios", "Gestión de devoluciones y reciclaje", "Área de picking exclusiva", "Parking para vehículos externos"], correctAnswerIndex: 1 },
    { questionText: "46. Los pasillos y zonas de tránsito no son espacios necesarios para el almacenaje.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    // Page 10
    { questionText: "47. En la recepción, después de la descarga, se emiten etiquetas y se distribuye la mercancía.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "48. Un almacén es un local para depositar mercancías para su posterior venta o distribución.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "49. ¿Qué materiales auxiliares se almacenan en un almacén industrial?", options: ["Solo productos finales", "Materiales de mantenimiento y embalajes", "Mercancía para cliente final", "Solo granjas para animales"], correctAnswerIndex: 1 },
    { questionText: "50. La flexibilidad y motivación no son características de un equipo eficaz.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "51. ¿Qué se entiende por aprovisionamiento?", options: ["Actividad de recibir devoluciones", "Proceso de adquisición y suministro de materiales o productos", "Operación exclusiva de picking", "Solo gestión de documentación administrativa"], correctAnswerIndex: 1 },
    { questionText: "52. El stock de seguridad sirve para evitar roturas de stock por variaciones en la demanda.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 11
    { questionText: "53. ¿Qué es el \"picking\"?", options: ["Selección y preparación de pedidos para clientes", "Recepción inicial de la mercancía", "Proceso de devolución de productos", "Control financiero de facturas"], correctAnswerIndex: 0 },
    { questionText: "54. El cross-docking consiste en almacenar mercancía durante largos periodos antes de su expedición.", options: ["Verdadero", "Falgo"], correctAnswerIndex: 1 },
    { questionText: "55. ¿Qué es un código QR?", options: ["Un código bidimensional que almacena más información que un código de barras tradicional", "Un documento para transporte internacional", "Un sistema de gestión administrativa", "Una norma de trazabilidad física"], correctAnswerIndex: 0 },
    { questionText: "56. El embalaje protege la mercancía durante transporte y almacenaje.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "57. ¿Qué significa FIFO?", options: ["First In, First Out (primero en entrar, primero en salir)", "Free Input, Free Output", "Fast Information for Operators", "Flexible Inventory for Orders"], correctAnswerIndex: 0 },
    // Page 12
    { questionText: "58. El método LIFO significa que la última mercancía en entrar es la primera en salir.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "59. ¿Qué es un stock obsoleto?", options: ["Productos deteriorados, caducados o que ya no tienen salida comercial", "Mercancía lista para cross-docking", "Pedidos en preparación", "Material auxiliar"], correctAnswerIndex: 0 },
    { questionText: "60. La rotación de stock mide la frecuencia con que un producto se repone en el almacén.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "61. ¿Qué permite el código EAN-13?", options: ["Identificación internacional de productos con 13 dígitos", "Gestión de personal en un almacén", "Elaboración de facturas", "Clasificación por familias"], correctAnswerIndex: 0 },
    { questionText: "62. Un layout de almacén bien diseñado facilita flujos y reduce tiempos.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 13
    { questionText: "63. ¿Qué es el cross-docking?", options: ["Técnica para evitar almacenamiento, distribuyendo directamente la mercancía", "Almacenaje prolongado en cámaras", "Método de rotación de stock", "Estrategia de motivación de personal"], correctAnswerIndex: 0 },
    { questionText: "64. El just in time consiste en producir o entregar lo necesario en el momento justo.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "65. ¿Qué se entiende por logística inversa?", options: ["Devolución, reciclaje o reaprovechamiento de productos", "Solo distribución al cliente", "Técnica de almacenamiento FIFO", "Embalaje para exportación"], correctAnswerIndex: 0 },
    { questionText: "66. La logística inversa no forma parte de la cadena de suministro.", options: ["Verdadero", "Falso"], correctAnswerIndex: 1 },
    { questionText: "67. ¿Qué herramienta facilita la comunicación electrónica entre empresas?", options: ["PDA", "EDI", "Código QR", "Palet"], correctAnswerIndex: 1 },
    // Page 14
    { questionText: "68. El EDI permite intercambiar documentos como pedidos y facturas de manera digital.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "69. ¿Qué es un KPI en logística?", options: ["Indicador clave de desempeño (Key Performance Indicator)", "Documento de aduanas", "Tipo de embalaje", "Método de etiquetado"], correctAnswerIndex: 0 },
    { questionText: "70. Los KPI ayudan a medir la eficacia de las operaciones logísticas.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "71. ¿Qué significa trazabilidad hacia atrás?", options: ["Seguir el recorrido del producto desde el cliente hasta el origen", "Solo controlar stock en almacén", "Método de rotación de mercancía", "Sinónimo de FIFO"], correctAnswerIndex: 0 },
    { questionText: "72. La trazabilidad hacia adelante consiste en conocer a quién se entregó cada lote.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "73. ¿Qué es la ergonomía en el almacén?", options: ["Adaptación del puesto de trabajo para mejorar seguridad y rendimiento", "Sistema de etiquetado", "Método de rotación LIFO", "Software de picking"], correctAnswerIndex: 0 },
    // Page 15
    { questionText: "74. La ergonomía busca reducir riesgos laborales y aumentar la eficiencia.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "75. ¿Qué documento se utiliza en la recepción de mercancía?", options: ["Albarán", "Factura proforma", "Código QR", "Layout"], correctAnswerIndex: 0 },
    { questionText: "76. El albarán es un documento que justifica la entrega de la mercancía.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "77. ¿Qué es un palet?", options: ["Plataforma que facilita manipulación y transporte de mercancías", "Documento aduanero", "Software de trazabilidad", "Indicador KPI"], correctAnswerIndex: 0 },
    { questionText: "78. El europalet mide 1200 x 800 mm.", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    // Page 16
    { questionText: "79. ¿Qué es un contenedor?", options: ["Caja de grandes dimensiones para transporte internacional de mercancías", "Documento de devolución", "Equipo de protección personal", "Etiqueta RFID"], correctAnswerIndex: 0 },
    { questionText: "80. Los contenedores marítimos permiten transporte intermodal (barco, tren, camión).", options: ["Verdadero", "Falso"], correctAnswerIndex: 0 },
    { questionText: "81. ¿Cuál es la función principal del \"Albarán\"?", options: ["Documento de pago.", "Confirmación de entrega y verificación de la mercancía.", "Cancelación del pedido.", "Horario de ruta para el transportista."], correctAnswerIndex: 1 },
    { questionText: "82. ¿Qué significa \"Orden descendente\" en las partes de trabajo?", options: ["Del empleado al jefe.", "Del jefe al empleado, indicando lo que debe hacer el empleado.", "Del cliente al proveedor.", "Ruta de transporte."], correctAnswerIndex: 1 },
    // Page 17
    { questionText: "83. ¿Para qué sirve la \"Nota de entrega\"?", options: ["Confirmación de pago.", "Trazabilidad interna, pedidos internos o por urgencia, generalmente sin valor.", "Inventario del almacén.", "Control de rotación."], correctAnswerIndex: 1 },
    { questionText: "84. En un albarán, ¿qué significa \"Portes pagado\"?", options: ["El cliente paga el transporte.", "El proveedor paga el transporte.", "Transporte gratuito.", "Cancelación del envío."], correctAnswerIndex: 1 },
    { questionText: "85. ¿Cuál es el primer documento en la trazabilidad de la documentación?", options: ["Picking list.", "Orden de pedido (del cliente al proveedor).", "Carta de porte.", "Factura."], correctAnswerIndex: 1 },
    { questionText: "86. ¿Qué significa el principio FiFo en la rotación?", options: ["Lo último que entra, lo primero que sale.", "Lo primero que entra, lo primero que sale.", "Lo primero que caduca, lo primero que sale.", "Lo más barato primero."], correctAnswerIndex: 1 },
    // Page 18
    { questionText: "87. Según la regla de Pareto, ¿qué representa la categoría A?", options: ["50% de referencias, 5% de rotación.", "20% de referencias, 80% de rotación (alta rotación).", "30% de referencias, 15% de rotación.", "Baja rotación."], correctAnswerIndex: 1 },
    { questionText: "88. ¿Cuál es una consecuencia negativa de una mala rotación?", options: ["Mejora en la ubicación.", "Incremento de movimientos para facilitar la rotación (aumento de costes).", "Alta ocupación del espacio.", "Menos stock fantasma."], correctAnswerIndex: 1 },
    { questionText: "89. ¿Qué actividades mejoran la facilidad de rotación?", options: ["Ignorar el stock.", "Frentear (frente), colocación en fondo, orden y limpieza.", "Acumular mercancía antigua.", "Ventas urgentes sin control."], correctAnswerIndex: 1 },
    { questionText: "90. ¿Qué causa el \"stock fantasma\"?", options: ["Buena ubicación.", "Mala ocupación del espacio y desaparición de mercancía.", "Alta rotación.", "Sistemas automáticos."], correctAnswerIndex: 1 },
    // Page 19
    { questionText: "91. ¿Cuál es la ventaja principal del \"Acceso Directo\" en sistemas de almacenaje?", options: ["Pocas referencias, muchas unidades por referencia.", "Muchas referencias, pocas unidades por referencia, accesibilidad a todas.", "Sin accesibilidad.", "Solo LiFo."], correctAnswerIndex: 1 },
    { questionText: "92. ¿Qué caracteriza al sistema \"Cantilever\"?", options: ["Dinámico por gravedad.", "Para productos largos, aprovechamiento del espacio malo, poco mantenimiento.", "Automático.", "En bloque."], correctAnswerIndex: 1 },
    { questionText: "93. ¿Qué describe al sistema \"Drive Through\"?", options: ["LiFo, un pasillo.", "FiFo, buen espacio (pero necesita 2 pasillos), poco mantenimiento, rígido.", "Ni FiFo ni LiFo.", "Solo alta rotación."], correctAnswerIndex: 1 },
    { questionText: "94. ¿Qué sistema requiere mucho mantenimiento y es muy rígido?", options: ["Estantería convencional.", "Sistemas automáticos (transelevadores), hasta 30m de altura, máximo mantenimiento.", "En bloque.", "Flow Rail."], correctAnswerIndex: 1 },
    // Page 20
    { questionText: "95. ¿Qué es el sistema \"Push Back\"?", options: ["FiFo, 2 pasillos.", "LiFo, buen espacio (1 pasillo), mucho mantenimiento, muy rígido.", "Acceso directo.", "Para productos largos."], correctAnswerIndex: 1 },
    { questionText: "96. ¿Qué es la Ley 31/1995?", options: ["Regulación de transporte.", "Prevención de riesgos laborales.", "Construcción de almacenes.", "Reglas de rotación."], correctAnswerIndex: 1 },
    { questionText: "97. ¿Qué define \"Riesgo laboral\"?", options: ["Posibilidad de que un trabajador sufra daño derivado del trabajo.", "Estado de salud.", "Enfermedad.", "Solo accidente."], correctAnswerIndex: 0 },
    { questionText: "98. ¿Cuál es una obligación del trabajador según la LPRL?", options: ["Ignorar riesgos.", "Usar correctamente máquinas, informar de riesgos, cooperar en seguridad.", "Solo formación.", "Ignorar al empresario."], correctAnswerIndex: 1 },
    // Page 21
    { questionText: "99. ¿Qué es un \"Accidente laboral\" en definición preventiva?", options: ["Enfermedad profesional.", "Suceso súbito no deseado que causa pérdidas a personas, propiedad o procesos.", "Estado de bienestar.", "Solo lesión corporal."], correctAnswerIndex: 1 },
    { questionText: "100. ¿Qué derecho tienen los trabajadores según los Arts. 14-23 de la LPRL?", options: ["Ignorar equipos de protección.", "Evaluación de riesgos, formación, medidas de emergencia.", "Solo pago de salarios.", "Cancelación de contratos."], correctAnswerIndex: 1 },
    { questionText: "101. ¿Cuál es la principal característica del sistema de \"Acceso Directo\"?", options: ["Pocas referencias y muchas unidades por referencia.", "Muchas referencias, pocas unidades por referencia y accesibilidad a todas las referencias.", "No accesibilidad a las referencias.", "Solo para productos de alta rotación."], correctAnswerIndex: 1 },
    { questionText: "102. ¿Qué describe al sistema de \"Alta Compactación\"?", options: ["Muchas referencias y accesibilidad total.", "Pocas referencias, muchas unidades por referencia y no accesibilidad a las referencias.", "Flexible para cualquier tipo de producto.", "Bajo mantenimiento siempre."], correctAnswerIndex: 1 },
    // Page 22
    { questionText: "103. ¿Cuáles son las características principales del \"Sistema de estantería convencional o Rack System\"?", options: ["FiFo, buen espacio, mucho mantenimiento.", "Ni FiFo, ni LiFo, ni FeFo; aprovechamiento del espacio malo, poco mantenimiento, sistema flexible.", "Solo para productos largos.", "Accesibilidad limitada."], correctAnswerIndex: 1 },
    { questionText: "104. ¿Para qué tipo de productos es adecuado el \"Sistema convencional\"?", options: ["Productos de baja rotación exclusivamente.", "Cualquier tipo, pero con rotación media o alta preferiblemente.", "Solo mercancías peligrosas.", "Productos caducados."], correctAnswerIndex: 1 },
    { questionText: "105. ¿Qué ventaja tiene el \"Sistema de estantería con base móvil (MovaRack)\"?", options: ["Malo aprovechamiento del espacio.", "Buen aprovechamiento del espacio (solo 1 pasillo), pero mucho mantenimiento.", "Ni FiFo ni LiFo.", "Para productos de baja rotación solo."], correctAnswerIndex: 1, imageUrl: 'https://i.postimg.cc/vH2JdYhn/Almacenaje-m-vil.jpg' },
    { questionText: "106. ¿Para qué se utiliza principalmente el \"Sistema Cantilever\"?", options: ["Productos pequeños y frágiles.", "Productos largos, con aprovechamiento del espacio malo y poco mantenimiento.", "Mercancías peligrosas.", "Alta compactación."], correctAnswerIndex: 1, imageUrl: 'https://i.postimg.cc/c4kpNxhn/Sistema-Cantilever.jpg' },
    { questionText: "107. ¿Cuáles son las características del \"Sistema Flow Rail\"?", options: ["FiFo, espacio muy bueno.", "Ni FiFo, ni LiFo, ni FeFo; aprovechamiento del espacio intermedio, mucho mantenimiento.", "Sin mantenimiento.", "Rígido para productos largos."], correctAnswerIndex: 1 },
    // Page 23
    { questionText: "108. ¿Qué rotación utiliza el \"Sistema en bloque\"?", options: ["FiFo.", "LiFo, con aprovechamiento del espacio muy bueno y sin mantenimiento.", "FeFo.", "Ni uno ni otro."], correctAnswerIndex: 1 },
    { questionText: "109. ¿Qué describe al \"Sistema Drive In\"?", options: ["FiFo, necesita 2 pasillos.", "LiFo, solo un espacio de carga, poco mantenimiento, rígido.", "Mucho mantenimiento.", "Flexible para cualquier referencia."], correctAnswerIndex: 1 },
    { questionText: "110. ¿Cuáles son las diferencias clave del \"Sistema Drive Through\" respecto al Drive In?", options: ["LiFo, un pasillo.", "FiFo, buen espacio pero necesita 2 pasillos, poco mantenimiento, rígido.", "Ni FiFo ni LiFo.", "Alto mantenimiento."], correctAnswerIndex: 1 },
    { questionText: "111. ¿Qué rotación y características tiene el \"Sistema Push Back\"?", options: ["FiFo, espacio intermedio.", "LiFo, buen espacio (1 pasillo), mucho mantenimiento, muy rígido.", "FeFo, sin mantenimiento.", "Para productos largos."], correctAnswerIndex: 1 },
    // Page 24
    { questionText: "112. ¿Qué ventaja ofrece el \"Sistema de estanterías dinámicas por gravedad\"?", options: ["LiFo, 1 pasillo.", "FiFo, espacio bueno (2 pasillos, una unidad de carga), mucho mantenimiento, muy rígido.", "Poco mantenimiento.", "Flexible."], correctAnswerIndex: 1 },
    { questionText: "113. ¿Qué incluye el \"Sistema Automático\" como transelevadores, miniload, bilateral o trilateral?", options: ["Solo LiFo, espacio malo.", "LiFo, FiFo o FeFo; buena espacio (hasta 30m altura), máximo mantenimiento, extremadamente rígido.", "Poco mantenimiento.", "Para baja rotación."], correctAnswerIndex: 1, imageUrl: 'https://i.postimg.cc/J4YfWrx1/Sistema-autom-ticos.jpg' },
    { questionText: "114. ¿Para qué rotación es ideal el \"Sistema Automático\"?", options: ["Baja rotación.", "Alta rotación.", "Sin rotación específica.", "Solo media."], correctAnswerIndex: 1, imageUrl: 'https://i.postimg.cc/J4YfWrx1/Sistema-autom-ticos.jpg' },
    { questionText: "115. ¿Qué es un \"Sistema Autoportante\"?", options: ["Estantería convencional con base móvil.", "Estructura integrada donde las estanterías forman parte del edificio, con alta rotación y mucho mantenimiento.", "Sistema manual.", "Para productos pequeños."], correctAnswerIndex: 1, imageUrl: 'https://i.postimg.cc/HsvqCYz7/Sistema-autoportante.jpg' },
    // Page 25
    { questionText: "116. ¿Qué norma regula el mantenimiento de los sistemas de almacenaje?", options: ["Ley 31/1995.", "UNE-EN 15635, que incluye un plan de mantenimiento e inspección visual diaria.", "OMS.", "Ninguna específica."], correctAnswerIndex: 1 },
    { questionText: "117. ¿Qué tipo de inspección se recomienda diariamente en los sistemas de almacenaje?", options: ["Técnica profunda por expertos.", "Visual diaria por personal del almacén, para anomalías visibles como deformaciones.", "Anual solo.", "Ninguna."], correctAnswerIndex: 1 },
    { questionText: "118. ¿Cuál es una consecuencia de un mal sistema de almacenaje según las notas?", options: ["Menos costes.", "Desaparición de mercancía (agujero negro, stock fantasma), mala ocupación del espacio.", "Mayor flexibilidad.", "Alta accesibilidad siempre."], correctAnswerIndex: 1 },
    { questionText: "119. ¿En qué se diferencia el \"Sistema en bloque\" de los automáticos?", options: ["Mucho mantenimiento vs. sin mantenimiento.", "LiFo, muy flexible y sin mantenimiento vs. máximo mantenimiento y rígido.", "FiFo vs. LiFo.", "Para muchas referencias vs. pocas."], correctAnswerIndex: 1 },
    { questionText: "120. ¿Qué sistema es más adecuado para productos de rotación baja según Pareto?", options: ["Automáticos de alta altura.", "En bloque o Drive In, para pocas referencias y muchas unidades.", "Convencional.", "Cantilever."], correctAnswerIndex: 1 },
    // Page 26
    { questionText: "121. ¿Qué sistema combina flexibilidad y bajo mantenimiento?", options: ["Sistemas automáticos.", "Estantería convencional.", "Push Back.", "Drive Through."], correctAnswerIndex: 1 },
    { questionText: "122. El almacén de materias auxiliares está destinado a almacenar:", options: ["Botes, botellas o cajas necesarios para empaquetar el producto final.", "Todo lo necesario para terminar el producto como: botones, cremalleras, etc.", "Los repuestos necesarios para que las máquinas no paren como: rodamientos, combustibles, aceites, etc."], correctAnswerIndex: 1 },
    { questionText: "123. El cross-dock es el almacén donde las mercancías permanecen de media un día hasta que son despachadas hacia su destino.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "124. En los muelles de carga y descarga nos encontramos los abrigos que:", options: ["Son un elemento que protege a los trabajadores de los muelles de las inclemencias del tiempo.", "Son el elemento fijo que envuelve las cajas de los camiones facilitando la carga y descarga.", "Son los elementos flexibles que envuelven las cajas de los camiones protegiendo la mercancía."], correctAnswerIndex: 2 },
    { questionText: "125. ¿Cuál de las siguientes opciones no la encontramos en las zonas auxiliares de un almacén?", options: ["Zona botiquín.", "Aseos.", "Almacén de materiales auxiliares."], correctAnswerIndex: 2 },
    // Page 27
    { questionText: "126. La ruptura de stock es la situación que me puede producir:", options: ["Incrementar las ventas.", "Perder clientes.", "Mejorar mi imagen de empresa."], correctAnswerIndex: 1 },
    { questionText: "127. Las entradas y salidas de un almacén se puede producir tanto de materias primas como de productos terminados y siempre vendrán del exterior.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 1 },
    { questionText: "128. Las mermas de las mercancías en los almacenes se producen por robos o roturas.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "129. El destinatario de la mercancía deberá realizar la descarga sin la presencia del transportista.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 1 },
    { questionText: "130. La principal ventaja del cross-docking será:", options: ["El elevado tiempo de permanencia de la mercancía.", "La ausencia de stock.", "Toda la mercancía viene paletizada y no se ha de descomponer."], correctAnswerIndex: 1 },
    // Page 28
    { questionText: "131. En la cadena de suministros intervienen las empresas productoras, distribuidoras y comercializadoras de productos.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "132. Se denomina stock a:", options: ["Todas las mercancías que pedimos a nuestros proveedores.", "La mercancía que se ubica en nuestros almacenes.", "La mercancía que se recibe en el almacén."], correctAnswerIndex: 1 },
    { questionText: "133. En el sistema drive-in la entrada y salida de palés se produce por el mismo lado:", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "134. Las estanterías ideales para mercancías voluminosas se denominan:", options: ["Compactas de paletización.", "Dinámicas.", "Cantilever."], correctAnswerIndex: 2 },
    { questionText: "135. Las dimensiones del europalé homologado son:", options: ["1300×800×145 mm", "1200×145×800 mm", "1200×800×145 mm"], correctAnswerIndex: 2 },
    { questionText: "136. ¿Cuál de las opciones no es un tipo de cross-docking?", options: ["Directo.", "Indirecto.", "Mixto."], correctAnswerIndex: 2 },
    // Page 29
    { questionText: "137. El picking consiste en recoger y agrupar todos los productos que un cliente nos ha pedido.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "138. No forma parte de la documentación de expedición:", options: ["Orden de picking.", "Factura.", "Albarán."], correctAnswerIndex: 1 },
    { questionText: "139. El cuello de botella es la situación que se produce cuando:", options: ["El almacén se encuentra lleno de mercancías.", "No se puede continuar el proceso productivo por falta de materiales.", "Estamos esperando que se inicie la producción."], correctAnswerIndex: 1 },
    { questionText: "140. Si en un almacén ubicamos las mercancías en el suelo obligatoriamente lo haremos en un sistema de almacenamiento.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 1 },
    { questionText: "141. Los sistemas pick to light y pick by voice son tecnologías que utilizan:", options: ["Señales luminosas únicamente.", "Señales luminosas y acústicas.", "Señales luminosas y verbales."], correctAnswerIndex: 1 },
    // Page 30
    { questionText: "142. En el equipo de trabajo:", options: ["Se realiza una labor similar de forma autónoma.", "No existe coordinación de tareas.", "Se realizan labores diferentes pero complementarias."], correctAnswerIndex: 2 },
    { questionText: "143. El término sinergia significa:", options: ["Siniestralidad.", "Entendimiento.", "Cooperación."], correctAnswerIndex: 2 },
    { questionText: "144. Formar un equipo de trabajo supone tiempo pero a la larga se observa cómo es un tiempo muy bien invertido, puesto que repercutirá en:", options: ["Mayor productividad.", "Mejor cooperación.", "Existirá un menor sentimiento de compromiso."], correctAnswerIndex: 0 },
    { questionText: "145. Entre las tareas que realiza un operario de almacén no se encuentra:", options: ["Se encarga de la limpieza del almacén.", "Tiene como tarea actualizar inventarios.", "Elabora el documento albarán que acompaña a la mercancía."], correctAnswerIndex: 2 },
    { questionText: "146. La comunicación en la empresa se producirá de manera:", options: ["Ascendente.", "Mixta.", "Diagonal."], correctAnswerIndex: 1 },
    // Page 31
    { questionText: "147. La comunicación horizontal es la que se produce entre:", options: ["Superiores.", "Departamentos.", "Con el exterior."], correctAnswerIndex: 1 },
    { questionText: "148. La confianza supone que cada trabajador ha de interiorizar que los compañeros del equipo desarrollan sus tareas de la mejor manera posible.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "149. Cuál de los siguientes indicadores no nos proporcionará información sobre la calidad de un servicio:", options: ["Eficacia.", "Puntualidad.", "Gestión."], correctAnswerIndex: 2 },
    { questionText: "150. El uso de las medidas de protección nos evitará:", options: ["Pago de multas.", "Pérdidas de rentabilidad.", "Ahorra de tiempo de trabajo."], correctAnswerIndex: 1 },
    { questionText: "151. La persona asertiva es capaz de transmitir sus inquietudes y a la vez defender su posición no respetando la opinión de otros.", options: ["Verdadero.", "Falso."], correctAnswerIndex: 1 },
    { questionText: "152. Cuál de las siguientes afirmaciones es incorrecta.", options: ["Cuando el espacio es limitado, el almacenamiento en altura no es la solución.", "El pavimento que tenemos en nuestro almacén será otro de los puntos a tener en cuenta puesto que su buen estado facilitará el tránsito por él y el movimiento de los equipos de cargas y mercancías.", "Tenemos la posibilidad de mecanizar o automatizar las estanterías del almacén."], correctAnswerIndex: 0 },
    // Page 32
    { questionText: "153. El método LIFO de gestión de existencias significa:", options: ["Las existencias introducidas serán sacadas oportunamente.", "El último que entra el primero que sale.", "El primero que entra el primero que sale."], correctAnswerIndex: 1 },
    { questionText: "154. De las siguientes afirmaciones señala la incorrecta. Los palés metálicos:", options: ["Tienen una gran resistencia.", "Su vida útil es corta.", "Soportan pesos entre 1000-1200 kg."], correctAnswerIndex: 1 },
    { questionText: "155. Existe la posibilidad de utilizar palés de cartón:", options: ["Verdadero.", "Falso."], correctAnswerIndex: 0 },
    { questionText: "156. Podemos diferenciar tres características de los envases. Señala la opción verdadera:", options: ["Envase primario se encuentra en completo contacto con el producto hasta su consumo.", "Envase primario envolverá varios envases secundarios o un pack de artículos.", "Envase primario. Nos facilita su manipulación, almacenaje, distribución o transporte."], correctAnswerIndex: 0 },
    { questionText: "157. De las siguientes características de los envases y embalajes señala la opción incorrecta.", options: ["Un buen envasado nos permitirá no tener pérdidas de producto.", "El envase será el medio de comunicación que exista entre el fabricante y el consumidor final.", "El estado de conservación del producto dentro del envase se hará con las mayores garantías sin evitar que entre en contacto con factores contaminantes."], correctAnswerIndex: 2 },
    // Page 33
    { questionText: "158. De los siguientes materiales de envases señala el más problemático por su composición y exposición al exterior:", options: ["Madera.", "Metal.", "Plástico."], correctAnswerIndex: 2 }
];